name: Python CI

on:
  push:
    branches: [ main, backend-api, data-model ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run lint (ruff)
      run: |
        pip install ruff
        ruff check .

    - name: Run tests
      run: |
        pip install pytest
        pytest || echo "No tests yet"
        continue-on-error: true